# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Appium
      run: |
        npm install -g appium
    - name: Start the Appium Server
      run: ./node_modules/.bin/appium
    - name: Poll for Appium Server to Start
      run: |
        until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/wd/hub/sessions); do
          sleep 5
        done    
    - name: Test with pytest
      env:
        TENANT: ${{secrets.TENANT}} 
        USER_NAME: ${{secrets.USER_NAME}} 
        PASSWORD: ${{secrets.PASSWORD}}
        REMOTE: ${{secrets.REMOTE}}
        SAUCELABS_USER_NAME: ${{secrets.SAUCELABS_USER_NAME}}
        SAUCELABS_PASSWORD: ${{secrets.SAUCELABS_PASSWORD}}
        API_KEY: ${{secrets.API_KEY}}
        DEVICE_ID: ${{secrets.DEVICE_ID}}      
      run: |
        pytest
